name: audit

on:
  workflow_dispatch

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version: "1.21.5"

    - name: Download Modules
      run: make download

    - name: Lint the Source Code
      run: make lint

    - name: Run Tests
      run: make test
