name: draft

on:
  workflow_dispatch

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version: "1.21.5"

    - name: Download Modules
      run: make download

    - name: Build a Binary
      run: make bin

    - name: Create an Artifact
      run: make artifact

    - name: Create a Draft
      run: make draft
